language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --coverage-text
